root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  args_bin = ["--dev", "./configs/main.json", "./build/outputs/dev.pdf"]
  bin = "./build/resumer"
  cmd = "go build -o ./build/resumer ./cmd/"
  delay = 0
  exclude_dir = ["build", "vendor", "out", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "json"]
  include_file = []
  kill_delay = "0s"
  log = "errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
