name: Portfolio built with Next.js

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm packages(npm ci) required to start project
        run: |
          npm ci
      - name: Build with Next.js
        run: npm run build:portfolio
