name: Portfolio built with Next.js
on:
  push:
    branches:
      - main
    paths:
      - portfolio/**
  pull_request:
    branches:
      - main
    paths:
      - portfolio/**
env:
  committer_name: Antigen
  committer_email: antigen.bot0@gmail.com
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm packages(npm ci) required to start project
        run: |
          npm ci
      - name: Deploy portfolio in Vercel
        run: npm run deploy:portfolio -- --yes --token=${{secrets.VERCEL_TOKEN}}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm packages(npm ci) required to start project
        run: |
          npm ci
      - name: Build with Next.js
        run: npm run build:portfolio
  ensure-styling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm packages(npm ci) required to start project
        run: npm ci
      - name: Modify the portfolio code using prettier.
        run: |
          shopt -s dotglob
          (cd ./portfolio && npx prettier --write "{*,**/*}.{js,ts,json,tsx,jsx}")
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          author: ${{env.committer_name}} <${{env.committer_email}}>
          committer: ${{env.committer_name}} <${{env.committer_email}}>
          branch: pstyling
          delete-branch: true
          title: |
            Actions: Automated prettier changes
          commit-message: 'style(actions): ran `npx prettier --write "{*,**/*}.{js,ts,json,tsx,jsx}"`'
          body: |
            Automated changes by a GitHub Action.
