name: Stylint

on: [push]

jobs:
    eslint:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - run: npm ci
            - run: npx eslint .

    prettier:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - run: npm ci
            - run: npx prettier --check "**/*.{js,json}"
