name: Stylint

on: [push, pull_request]

jobs:
    eslint:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 20
            - run: npm ci
            - run: npx eslint .

    prettier:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 20
            - run: npm ci
            - run: npx prettier --check "**/*.{js,json}"

    # golangci:
    #     runs-on: ubuntu-20.04
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-go@v3
    #           with:
    #               go-version: '>=1.20.0'
    #         - name: golangci-lint
    #           uses: golangci/golangci-lint-action@v3
    #           with:
    #               version: latest
    #               args: --issues-exit-code=1
    #               working-directory: resume

    # gofumpt:
    #     runs-on: ubuntu-20.04
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-go@v3
    #           with:
    #               go-version: '>=1.19.0'
    #         - run: go install mvdan.cc/gofumpt@latest
    #         - name: Check code format
    #           run: |
    #               output=$(gofumpt -l -w -s .)
    #               if [ -n "$output" ]; then
    #                   echo "\033[38;2;217;33;57mCode format errors detected in:"
    #                   echo "$output\033[0m"
    #                   exit 1
    #               fi
