name: Stylint

on: [push]

jobs:
    eslint:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - run: npm ci
            - run: npx eslint .

    golangci:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v3
              with:
                  go-version: ">=1.20.0"
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest
                  args: --issues-exit-code=1
                  working-directory: resume

    prettier:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - run: npm ci
            - run: npx prettier --check "**/*.{js,json}"
